packages:
  - packages/*

engineStrict: true
pmOnFail: error
verifyDepsBeforeRun: error
saveExact: true
strictPeerDependencies: true
autoInstallPeers: false
storeDir: .pnpm-store
cacheDir: .cache/pnpm
allowBuilds: {}
