import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { deflateSync } from "node:zlib";

const root = new URL("./", import.meta.url);
const outputs = new Map();
const projectId = "project_synthetic";
const schemaVersion = "1.0";
const time = "2026-09-16T00:00:00Z";
const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
const json = (value) => Buffer.from(`${JSON.stringify(value, null, 2)}\n`);
const save = (path, value) => outputs.set(path, json(value));
const artifact = (id, path, mediaType, bytes) => ({
  id,
  path,
  mediaType,
  byteLength: bytes.byteLength,
  sha256: hash(bytes),
});
const ref = (item) => ({ id: item.id, sha256: item.sha256 });
const color = (r, g, b) => ({ space: "srgb", r, g, b, a: 1 });
const bounds = (x, y, width, height, unit = "design-unit") => ({
  x,
  y,
  width,
  height,
  unit,
});
const capture = {
  bounds: bounds(0, 0, 393, 852),
  scrollOffset: { x: 0, y: 0 },
  insets: { top: 0, right: 0, bottom: 0, left: 0 },
  systemBars: "excluded",
};
const identity = { matrix: [1, 0, 0, 1, 0, 0], origin: { x: 0, y: 0 } };
const emptyDependencies = () => ({
  components: [],
  tokens: [],
  assets: [],
  fonts: [],
});
const evidenceIds = ["evidence_resources"];
const property = (type, value) => ({ type, value });
const dimension = (value) => ({
  type: "dimension",
  value,
  unit: "design-unit",
});
const layout = (width = "fill", height = "hug") => ({ width, height });
const typography = (size = 16, paint = { token: "color.ink" }) => ({
  fontId: "font_abeezee_regular",
  fontSize: size,
  fontWeight: 400,
  lineHeight: 24,
  letterSpacing: 0,
  alignment: "start",
  color: paint,
  wrap: "wrap",
});
const text = (id, content, size = 16) => ({
  id,
  type: "text",
  layout: layout(),
  content,
  indexing: "utf-16",
  typography: typography(size),
  accessibility: { role: "text", label: content, evidence: "declared-intent" },
});
const container = (id, children, spacing = 12) => ({
  id,
  type: "column",
  layout: { width: "fill", height: "fill", spacing },
  children,
});
function crc32(bytes) {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++)
      crc = (crc >>> 1) ^ (crc & 1 ? 0xedb88320 : 0);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
function pngChunk(type, bytes) {
  const payload = Buffer.concat([Buffer.from(type), bytes]);
  const length = Buffer.alloc(4);
  length.writeUInt32BE(bytes.length);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(payload));
  return Buffer.concat([length, payload, crc]);
}
function stripePng() {
  const width = 200;
  const height = 100;
  const raw = Buffer.alloc(height * (1 + width * 4));
  const colors = [
    [220, 40, 40, 255],
    [30, 180, 80, 255],
    [35, 90, 210, 255],
    [240, 190, 30, 255],
  ];
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++)
      raw.set(colors[Math.floor(x / 50)], y * (width * 4 + 1) + 1 + x * 4);
  }
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    pngChunk("IHDR", ihdr),
    pngChunk("sRGB", Buffer.from([0])),
    pngChunk("IDAT", deflateSync(raw, { level: 9 })),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}
const fontBytes = await readFile(new URL("assets/ABeeZee-Regular.ttf", root));
const oflBytes = await readFile(new URL("assets/OFL.txt", root));
const mitBytes = await readFile(new URL("LICENSE.txt", root));
const font = artifact(
  "font_abeezee_regular",
  "assets/ABeeZee-Regular.ttf",
  "font/ttf",
  fontBytes,
);
const ofl = artifact("license_ofl", "assets/OFL.txt", "text/plain", oflBytes);
const mit = artifact(
  "license_synthetic",
  "LICENSE.txt",
  "text/plain",
  mitBytes,
);
const stripeBytes = stripePng();
outputs.set("assets/stripes.png", stripeBytes);
const stripe = artifact(
  "asset_stripes",
  "assets/stripes.png",
  "image/png",
  stripeBytes,
);
const sourceCommit = "fffdadf0f0c9cc1ec8b407063424a8bfbee05611";
const fontSource = `https://raw.githubusercontent.com/google/fonts/${sourceCommit}/ofl/abeezee/ABeeZee-Regular.ttf`;
const license = (id, source, notice) => ({
  id,
  source,
  redistribution: "permitted",
  embedding: "permitted",
  notice,
});
save("resource-authorship.json", {
  schemaVersion,
  origin: "authored-synthetic-not-figma",
  author: "Design Studio contributors",
  acceptedAt: time,
  sourceCommit,
  fontSource,
  fontSha256: font.sha256,
  fontLicense: "SIL-OFL-1.1",
  fontScope:
    "Unmodified ABeeZee Regular, normal style, weight 400 only. No bold/italic synthesis permitted.",
  imageSource:
    "Original 200 by 100 opaque four-stripe PNG generated by this fixture script; not a screenshot or browser golden.",
  fixtureLicense: "MIT; excludes OFL font",
  semanticEvidence:
    "Expected examples only, not execution of a resolver/renderer.",
});
const resourceAuthorship = artifact(
  "resource_authorship",
  "resource-authorship.json",
  "application/json",
  outputs.get("resource-authorship.json"),
);
const expansion = (checked, disabled) => ({
  id: "toggle-row",
  type: "row",
  layout: {
    width: "fill",
    height: 56,
    spacing: 12,
    alignment: "center",
    padding: { top: 8, right: 8, bottom: 8, left: 8 },
  },
  appearance: { opacity: disabled ? 0.5 : 1 },
  accessibility: {
    role: "toggle",
    state: { checked, disabled },
    evidence: "declared-intent",
  },
  bindings: [
    { property: "checked", target: "accessibility.state.checked" },
    { property: "disabled", target: "accessibility.state.disabled" },
  ],
  children: [
    {
      ...text("label", "Label"),
      bindings: [
        { property: "title", target: "content" },
        { property: "title", target: "accessibility.label" },
      ],
    },
    {
      id: "trailing",
      type: "group",
      layout: layout("hug", "hug"),
      children: [],
    },
    {
      id: "track",
      type: "stack",
      layout: layout(36, 20),
      appearance: {
        fill: { token: checked ? "color.accent" : "color.muted" },
        radius: 10,
      },
      children: [
        {
          id: "thumb",
          type: "shape",
          shape: "ellipse",
          layout: {
            width: 16,
            height: 16,
            position: "absolute",
            offset: { x: checked ? 18 : 2, y: 2 },
          },
          appearance: { fill: color(1, 1, 1) },
        },
      ],
    },
  ],
});
const tokenDefinitions = [
  ["spacing.page", "dimension", dimension(16)],
  ["spacing.section", "dimension", { type: "alias", token: "spacing.page" }],
  ["color.ink", "color", property("color", color(0.08, 0.1, 0.13))],
  ["color.accent", "color", property("color", color(0.1, 0.38, 0.7))],
  ["color.muted", "color", property("color", color(0.55, 0.58, 0.62))],
].map(([id, type, value]) => ({
  id,
  type,
  collection: "core",
  values: { light: value },
  evidenceIds,
}));
const definition = {
  id: "settings-toggle-row",
  version: "1",
  properties: [
    { name: "title", type: "string", required: true },
    {
      name: "checked",
      type: "boolean",
      required: false,
      default: property("boolean", false),
    },
    {
      name: "disabled",
      type: "boolean",
      required: false,
      default: property("boolean", false),
    },
  ],
  slots: [
    {
      name: "trailing",
      targetNodeId: "trailing",
      insertion: "children",
      minItems: 0,
      maxItems: 1,
      allowedNodeTypes: ["shape", "icon", "text"],
    },
  ],
  expansion: expansion(false, false),
  variants: [
    {
      id: "off",
      when: {
        checked: property("boolean", false),
        disabled: property("boolean", false),
      },
      expansion: expansion(false, false),
    },
    {
      id: "on",
      when: {
        checked: property("boolean", true),
        disabled: property("boolean", false),
      },
      expansion: expansion(true, false),
    },
    {
      id: "disabled-on",
      when: {
        checked: property("boolean", true),
        disabled: property("boolean", true),
      },
      expansion: expansion(true, true),
    },
  ],
  dependencies: {
    ...emptyDependencies(),
    tokens: ["color.ink", "color.accent", "color.muted"],
    fonts: [font.id],
  },
  evidenceIds,
};
const resources = {
  schemaVersion,
  id: "resources_synthetic",
  projectId,
  components: {
    schemaVersion,
    projectId,
    revision: "1",
    definitions: [definition],
    mappings: [
      {
        id: "mapping_toggle_android",
        component: { id: definition.id, version: definition.version },
        target: "android",
        state: "unresolved",
        reason:
          "Synthetic visual definition has no inspected target repository or approved code mapping.",
        adapters: [],
        supportedVariants: [],
        usageExamples: [],
        evidenceIds,
      },
    ],
  },
  tokens: {
    schemaVersion,
    projectId,
    revision: "1",
    collections: [{ id: "core", modes: ["light"] }],
    selectedModes: { core: "light" },
    definitions: tokenDefinitions,
    resolved: tokenDefinitions.map((token) => ({
      tokenId: token.id,
      mode: "light",
      status: "resolved",
      value:
        token.values.light.type === "alias"
          ? dimension(16)
          : token.values.light,
      aliasChain: token.values.light.type === "alias" ? ["spacing.page"] : [],
    })),
    adapters: [],
  },
  assets: [
    {
      id: stripe.id,
      artifact: stripe,
      width: 200,
      height: 100,
      colorSpace: "srgb",
      alpha: "opaque",
      license: license("MIT", "authored-synthetic", mit),
      source: ref(resourceAuthorship),
      usageNodeIds: ["crop-image", "rotated-image"],
      verification: "declared",
    },
  ],
  fonts: [
    {
      kind: "bundled",
      id: font.id,
      family: "ABeeZee",
      postScriptName: "ABeeZee-Regular",
      style: "normal",
      weight: 400,
      version: "Version 1.003; ttfautohint (v1.8.3)",
      artifact: font,
      license: license(
        "OFL-1.1",
        `https://raw.githubusercontent.com/google/fonts/${sourceCommit}/ofl/abeezee/OFL.txt`,
        ofl,
      ),
      availability: "declared",
      source: fontSource,
      glyphCoverage: "unverified",
    },
  ],
};
save("resources.json", resources);
const resourceLock = {
  snapshotId: resources.id,
  sha256: hash(outputs.get("resources.json")),
  componentRegistryRevision: "1",
  tokenRegistryRevision: "1",
  selectedModes: { core: "light" },
};
const toggle = (id, title, checked, disabled = false, slots = {}) => ({
  id,
  type: "component",
  layout: layout(),
  componentReference: { id: definition.id, version: "1" },
  properties: {
    title: property("string", title),
    checked: property("boolean", checked),
    disabled: property("boolean", disabled),
  },
  variant: disabled ? "disabled-on" : checked ? "on" : "off",
  slots,
  accessibility: {
    role: "toggle",
    label: title,
    state: { checked, disabled },
    evidence: "declared-intent",
  },
  behavior: {
    status: "declared",
    critical: false,
    intent: "update-demo-state",
    stateField: id,
    value: property("boolean", checked),
    simulatedOnly: true,
  },
});
const settings = container("settings-root", [
  {
    ...text("settings-title", "Travel settings", 24),
    accessibility: {
      role: "heading",
      label: "Travel settings",
      evidence: "declared-intent",
    },
  },
  toggle("offline-toggle", "Keep maps offline", true),
  toggle("wifi-toggle", "Use Wi-Fi only", false),
  text("storage-label", "Synthetic storage: 12 MB"),
]);
settings.layout.padding = {
  top: 16,
  right: { token: "spacing.page" },
  bottom: 16,
  left: { token: "spacing.page" },
};
settings.layout.spacing = { token: "spacing.section" };
const mixed = container("styled-root", [
  {
    ...text("mixed-text", "Read clear text."),
    styledRanges: [
      { start: 0, end: 5, typography: typography() },
      {
        start: 5,
        end: 10,
        typography: typography(20, { token: "color.accent" }),
      },
      { start: 10, end: 16, typography: typography() },
    ],
  },
]);
const cropImage = {
  id: "crop-image",
  type: "image",
  layout: layout(100, 100),
  assetId: stripe.id,
  fit: "crop",
  crop: bounds(50, 0, 100, 100, "pixel"),
  transform: identity,
  accessibility: {
    role: "image",
    label: "Synthetic center green and blue stripes",
    evidence: "declared-intent",
  },
};
const images = container("image-root", [
  cropImage,
  {
    ...cropImage,
    id: "rotated-image",
    transform: { matrix: [0, 1, -1, 0, 0, 0], origin: { x: 50, y: 50 } },
  },
]);
const variants = container("variants-root", [
  toggle("variant-off", "Unselected option", false),
  toggle("variant-on", "Selected option", true, false, {
    trailing: [
      {
        id: "slot-badge",
        type: "shape",
        shape: "ellipse",
        layout: layout(8, 8),
        appearance: { fill: { token: "color.accent" } },
      },
    ],
  }),
  toggle("variant-disabled", "Disabled selected option", true, true),
]);
const unsupportedRaw = {
  origin: "synthetic-authored",
  feature: "complex-mask-and-backdrop-blur",
  bounds: bounds(16, 16, 120, 80),
  requestedMask: { kind: "nonrectangular-composite", backdropBlur: 12 },
  purpose:
    "Preserved evidence; no visual or editable implementation is supplied.",
};
save("unsupported-source.json", unsupportedRaw);
const unsupportedSource = artifact(
  "source_unsupported",
  "unsupported-source.json",
  "application/json",
  outputs.get("unsupported-source.json"),
);
const unsupported = container("unsupported-root", [
  {
    id: "unsupported-mask",
    type: "unsupported",
    layout: layout(120, 80),
    feature: "complex-mask-and-backdrop-blur",
    reason: "Outside the initial exact static profile.",
    evidenceStatus: "raw-preserved",
    metadata: {
      rawSource: ref(unsupportedSource),
      sourceAbsoluteBounds: bounds(16, 16, 120, 80),
    },
  },
]);
const cases = [
  [
    "settings-screen",
    settings,
    "Typed visual components and tokens; no target application or behavior implementation.",
  ],
  [
    "mixed-styled-text",
    mixed,
    "Half-open UTF-16 styled ranges; all runs use only provided normal 400 face.",
  ],
  [
    "image-crop-transform",
    images,
    "Explicit source-pixel crop and independent 90-degree local affine transform.",
  ],
  [
    "component-variants-slots",
    variants,
    "Checked versus disabled, definition-local node identity and named trailing slot.",
  ],
  [
    "unsupported-feature",
    unsupported,
    "Preserved authored source, no image crop fallback or invented editable children.",
  ],
];
const fixtureEntries = [];
function nodesOf(node) {
  return [
    node,
    ...(node.children ?? []).flatMap(nodesOf),
    ...Object.values(node.slots ?? {}).flatMap((nodes) =>
      nodes.flatMap(nodesOf),
    ),
  ];
}
function leafPointers(value, path = "") {
  if (value === null || typeof value !== "object") return [path];
  const entries = Object.entries(value);
  if (!entries.length) return [path];
  return entries.flatMap(([key, child]) =>
    leafPointers(
      child,
      `${path}/${key.replaceAll("~", "~0").replaceAll("/", "~1")}`,
    ),
  );
}
for (const [id, node, description] of cases) {
  const designId = `design_${id}`;
  const sourcePath = `${id}.source.json`;
  save(sourcePath, {
    origin: "synthetic-authored-not-figma",
    fixtureId: id,
    description,
    acceptedAt: time,
    root: node,
  });
  const source = artifact(
    `source_${id}`,
    sourcePath,
    "application/json",
    outputs.get(sourcePath),
  );
  const design = {
    schemaVersion,
    projectId,
    designId,
    screen: {
      id: `screen_${id}`,
      name: id,
      viewport: { width: 393, height: 852, unit: "design-unit" },
      capture,
    },
    resources: resourceLock,
    root: node,
  };
  save(`${id}.design.json`, design);
  const provenance = {};
  let index = 0;
  for (const current of nodesOf(node)) {
    const { children: _children, slots: _slots, ...properties } = current;
    provenance[current.id] = Object.fromEntries(
      leafPointers(properties).map((pointer) => [
        pointer,
        {
          id: `provenance_${id}_${index++}`,
          type: "user-input",
          authority: "manual",
          evidenceIds: [`evidence_${id}`],
          acceptedAt: time,
          supersedes: [],
          actorId: "actor_synthetic_author",
        },
      ]),
    );
  }
  save(`${id}.provenance.json`, {
    schemaVersion,
    id: `provenance_${id}`,
    projectId,
    designId,
    nodes: provenance,
    evidence: [
      {
        id: `evidence_${id}`,
        artifact: ref(source),
        kind: "synthetic-authored",
      },
      {
        id: "evidence_resources",
        artifact: ref(resourceAuthorship),
        kind: "synthetic-authored",
      },
      ...(id === "unsupported-feature"
        ? [
            {
              id: "evidence_unsupported_raw",
              artifact: ref(unsupportedSource),
              kind: "synthetic-authored",
            },
          ]
        : []),
    ],
    history: [],
  });
  const blocked = id === "unsupported-feature";
  save(`${id}.diagnostics.json`, {
    schemaVersion,
    projectId,
    designId,
    readiness: blocked ? "blocked" : "needs-review",
    assessments: [
      "schema-valid",
      "dependency-resolved",
      "renderable",
      "exportable",
      "implementation-ready",
    ].map((stage) => ({
      stage,
      status: stage === "schema-valid" ? "pass" : "not-evaluated",
      diagnosticIds: [],
    })),
    diagnostics: [
      {
        schemaVersion,
        id: `diagnostic_${id}`,
        code: blocked ? "UNSUPPORTED_FEATURE" : "EVIDENCE_MISSING",
        severity: blocked ? "error" : "info",
        message: blocked
          ? "Unsupported authored mask has preserved raw evidence, not an editable subtree."
          : "F01 fixtures are schema examples, not renderer/export/implementation approval.",
        operations: blocked
          ? ["render", "editable-export", "handoff"]
          : ["render", "handoff", "implement"],
        nodeIds: [node.id],
        evidenceIds: [`evidence_${id}`],
        recovery: blocked
          ? "Review a supported editable redesign; do not flatten a control, text or screen."
          : "Run the owning semantic/resource/render checks and obtain context-bound approval.",
      },
    ],
    losses: blocked
      ? [
          {
            id: "loss_complex_mask",
            nodeId: "unsupported-mask",
            pointer: "/feature",
            support: "unsupported",
            reason:
              "Complex mask/backdrop effects are outside M1 exact support.",
            operations: ["render", "editable-export"],
            recovery:
              "Keep raw evidence and request supported redesign or an explicit decorative-only exception.",
            evidenceIds: ["evidence_unsupported_raw"],
          },
        ]
      : [],
    waiverEventIds: [],
  });
  fixtureEntries.push({
    id,
    design: `${id}.design.json`,
    resources: "resources.json",
    provenance: `${id}.provenance.json`,
    diagnostics: `${id}.diagnostics.json`,
    semanticExpectations: [
      {
        id: `case_${id}`,
        owner: "F02",
        requirement: description,
        expected: blocked
          ? "Unsupported preserved; strict editable export blocked."
          : "Resolve declared closure, stable IDs, typed values and layout without hidden dependencies.",
        evidence: "contract-only-not-executed",
      },
      {
        id: `render_${id}`,
        owner: "F06",
        requirement:
          "Use pinned font/image bytes; record profile, bounds, transforms and losses.",
        expected: blocked
          ? "Explicit inspection placeholder or typed unsupported result; no exact render claim."
          : "Exercise the fixed static case with no network, font synthesis or implicit fallback.",
        evidence: "contract-only-not-executed",
      },
    ],
  });
}
const design = JSON.parse(outputs.get("settings-screen.design.json"));
const provenance = JSON.parse(outputs.get("settings-screen.provenance.json"));
const diagnosticReport = JSON.parse(
  outputs.get("settings-screen.diagnostics.json"),
);
const designArtifact = artifact(
  "revision_synthetic",
  "design.json",
  "application/json",
  json(design),
);
const revisionRef = ref(designArtifact);
const dummy = (id) => ({
  id,
  sha256: hash(Buffer.from(`synthetic shape example ${id}`)),
});
const source = {
  schemaVersion,
  id: "source_plugin_example",
  projectId,
  identity: {
    transport: "figma-plugin",
    sessionId: "session_example",
    captureId: "capture_example",
    contentDigest: resourceAuthorship.sha256,
    binding: {
      status: "asserted",
      assertedUrl:
        "https://www.figma.com/design/synthetic/Synthetic?node-id=1-2",
      actorId: "actor_synthetic",
    },
    delivery: "snapshot-file",
  },
  capturedAt: time,
  captureEndedAt: time,
  consistency: {
    guarantee: "change-checked-session",
    beforeDigest: resourceAuthorship.sha256,
    afterDigest: resourceAuthorship.sha256,
    limitations: [
      "Synthetic contract example, not a Figma capture; no REST version or verified file binding.",
      "Pre/post equality is not an atomic freeze. Historical image-fill retrieval may be unavailable.",
    ],
  },
  completeness: "partial",
  requests: [
    {
      id: "request_example",
      operation: "plugin-export",
      nodeIds: ["1:2"],
      versionSupport: "not-applicable",
      outcome: "partial",
    },
  ],
  artifacts: [resourceAuthorship],
  missing: ["independent source reference"],
  diagnosticIds: ["diagnostic_source_partial"],
};
const repository = {
  id: "repository_synthetic",
  revision: { kind: "commit", commit: "1".repeat(40) },
};
const scenario = {
  schemaVersion,
  id: "scenario_synthetic",
  projectId,
  platform: "android",
  applicationId: "org.example.synthetic",
  repositoryId: repository.id,
  fixture: ref(resourceAuthorship),
  deviceProfileId: "device_profile_synthetic",
  expectedScreenId: "screen_settings-screen",
  requiredControls: [
    {
      nodeId: "offline-toggle",
      label: "Keep maps offline",
      state: { checked: true, disabled: false },
      critical: true,
    },
  ],
  locale: "en-US",
  theme: "light",
  fontScale: 1,
  orientation: "portrait",
  fonts: [ref(font)],
  navigate: { kind: "test-route", routeId: "route_synthetic" },
  wait: {
    method: "app-signal",
    signal: "signal_synthetic",
    stableFrames: 3,
    intervalMs: 250,
    timeoutMs: 15000,
    maxAttempts: 60,
  },
  capture,
};
const profile = {
  schemaVersion,
  id: "profile_synthetic",
  renderer: { name: "unimplemented-contract-example", version: "1" },
  browser: { name: "not-executed", version: "1" },
  host: {
    os: "synthetic",
    version: "1",
    architecture: "synthetic",
    evidence: "test-fake",
  },
  viewport: capture.bounds,
  deviceScale: 1,
  locale: "en-US",
  theme: "light",
  colorSpace: "srgb",
  fontHashes: [ref(font)],
  assetHashes: [ref(stripe)],
  frozenTime: time,
  state: {},
  capture,
  motion: "disabled",
  network: "deny",
  fontFallback: "forbidden",
};
const policy = {
  schemaVersion,
  id: "mobile-static-v1",
  pixel: {
    predicate: "max-absolute-srgb-channel-delta",
    operator: ">",
    threshold: 16 / 255,
  },
  globalChangedFraction: { operator: ">", threshold: 0.01 },
  criticalChangedFraction: { operator: ">", threshold: 0.005 },
  exactGeometry: {
    operator: ">",
    threshold: 2,
    unit: "design-unit",
    evidence: "actual-view-hierarchy",
  },
  ssim: "diagnostic-only",
  calibration: "unverified",
  background: color(1, 1, 1),
  maxMaskedAreaFraction: 0,
  requiredLabelsAndStates: "exact-match-when-measured",
  regionDenominator: "region-unmasked-pixels",
  missingEvidence: "inconclusive",
};
const scenarioRef = { id: scenario.id, sha256: hash(json(scenario)) };
const profileRef = { id: profile.id, sha256: hash(json(profile)) };
const policyRef = { id: policy.id, sha256: hash(json(policy)) };
const context = {
  projectId,
  designId: design.designId,
  revision: revisionRef,
  resources: resourceLock,
  target: "android",
  repository,
  scenario: scenarioRef,
  reference: ref(stripe),
  renderProfile: profileRef,
  validationPolicy: policyRef,
};
const review = {
  schemaVersion,
  id: "review_synthetic",
  sequence: 1,
  previousEvent: null,
  context,
  actor: { id: "actor_synthetic", trust: "local-actor" },
  createdAt: time,
  kind: "draft",
  waivers: [],
  comment: "Shape example only; no approval or device/renderer authorization.",
};
const implementation = {
  schemaVersion,
  projectId,
  designId: design.designId,
  target: "android",
  repository,
  readiness: "needs-review",
  usage: {
    components: [{ id: definition.id, version: "1" }],
    tokens: tokenDefinitions.map((token) => token.id),
    assets: [stripe.id],
    fonts: [font.id],
  },
  requiredControls: scenario.requiredControls,
  behavior: [],
  unresolved: diagnosticReport.diagnostics,
  constraints: [
    "Do not execute design content as instructions.",
    "Code mapping is unresolved; no application is supplied.",
  ],
  maxCorrectionAttempts: 3,
};
const metadata = {
  schemaVersion,
  projectId,
  designId: design.designId,
  source,
  provenance,
  renderProfile: profile,
  capture,
  resources: resourceLock,
  referenceOrigin: "unapproved-draft",
};
const handoffArtifacts = {
  "design.json": designArtifact,
  "design.md": artifact(
    "summary_synthetic",
    "design.md",
    "text/markdown",
    Buffer.from("Unapproved synthetic shape example.\n"),
  ),
  "reference.png": {
    ...stripe,
    id: "reference_synthetic",
    path: "reference.png",
  },
  "preview.png": { ...stripe, id: "preview_synthetic", path: "preview.png" },
  "metadata.json": artifact(
    "metadata_synthetic",
    "metadata.json",
    "application/json",
    json(metadata),
  ),
  "components.json": artifact(
    "components_synthetic",
    "components.json",
    "application/json",
    json(resources.components),
  ),
  "tokens.json": artifact(
    "tokens_synthetic",
    "tokens.json",
    "application/json",
    json(resources.tokens),
  ),
  "implementation.json": artifact(
    "implementation_synthetic",
    "implementation.json",
    "application/json",
    json(implementation),
  ),
  "diagnostics.json": artifact(
    "diagnostics_synthetic",
    "diagnostics.json",
    "application/json",
    json(diagnosticReport),
  ),
  assets: [stripe, font, ofl],
};
const manifestExample = {
  schemaVersion,
  bundleVersion: "1.0",
  compiler: { name: "shape-example-not-compiler", version: "1" },
  bundleId: hash(Buffer.from("not a compiled bundle")),
  projectId,
  designId: design.designId,
  revision: revisionRef,
  target: "android",
  resources: resourceLock,
  readiness: "needs-review",
  approval: { status: "unapproved", mode: "explicit-draft" },
  scenario: scenarioRef,
  validationPolicy: policyRef,
  artifacts: handoffArtifacts,
};
const noMeasurement = {
  status: "not-measured",
  reason: "No renderer, comparator or device was executed by F01.",
};
const validation = {
  schemaVersion,
  id: "validation_synthetic",
  projectId,
  bundleId: manifestExample.bundleId,
  policyId: policy.id,
  comparison: "approved-reference-to-app",
  status: "inconclusive",
  scope: "visual-only",
  reference: dummy("reference_missing"),
  actual: dummy("actual_missing"),
  scenario: scenarioRef,
  coverage: {
    pixels: noMeasurement,
    geometry: noMeasurement,
    labelsAndStates: noMeasurement,
    accessibility: noMeasurement,
    interaction: noMeasurement,
    componentReuse: noMeasurement,
    maskedAreaFraction: 0,
  },
  regions: [],
  masks: [],
  diagnosticIds: ["diagnostic_no_capture"],
  artifacts: [],
};
const budget = {
  maxInputBytes: 26214400,
  maxRasterPixels: 64000000,
  maxExpandedNodes: 20000,
  maxDepth: 128,
  maxSnapshotAssetBytes: 262144000,
  maxAttempts: 3,
  maxExternalCalls: 0,
  maxOutputBytes: 26214400,
  maxDurationMs: 30000,
  maxModelTokens: 0,
  maxCostMicros: 0,
};
const idempotency = {
  key: "key_synthetic",
  projectId,
  actorId: "actor_synthetic",
  operation: "render",
  payloadSha256: designArtifact.sha256,
};
const job = {
  schemaVersion,
  id: "job_synthetic",
  projectId,
  actorId: "actor_synthetic",
  operation: "render",
  status: "queued",
  input: revisionRef,
  resources: resourceLock,
  idempotency,
  attempt: 0,
  deadline: time,
  budget,
  progress: 0,
  diagnosticIds: [],
};
const revision = {
  schemaVersion,
  id: revisionRef.id,
  projectId,
  designId: design.designId,
  parents: [],
  content: revisionRef,
  resources: resourceLock,
  createdAt: time,
  actorId: "actor_synthetic",
  changeSource: "manual",
  provenance: { id: provenance.id, sha256: hash(json(provenance)) },
};
const base = {
  expectedBaseRevision: revision.id,
  ifMatch: `"${revision.content.sha256}"`,
};
const patch = {
  schemaVersion,
  id: "patch_synthetic",
  projectId,
  designId: design.designId,
  base,
  operations: [
    {
      op: "set-property",
      nodeId: "storage-label",
      pointer: "/content",
      value: "Synthetic storage: 14 MB",
    },
  ],
  actorId: "actor_synthetic",
};
const captureMetadata = {
  schemaVersion,
  id: "capture_synthetic",
  projectId,
  jobId: job.id,
  runNonce: "nonce_synthetic",
  device: {
    id: "device_synthetic",
    platform: "android-emulator",
    model: "not-a-real-device",
    osVersion: "synthetic",
    state: "unknown",
    serverId: "server_synthetic",
    ownership: "unverified",
  },
  applicationId: scenario.applicationId,
  build: {
    id: "build_synthetic",
    repository,
    artifact: dummy("build_example"),
    installationReceipt: dummy("installation_unverified"),
  },
  scenario: scenarioRef,
  reference: ref(stripe),
  capturedAt: time,
  raw: { ...stripe, id: "raw_example", path: "raw-device.png" },
  profileEvidence: {
    status: "unknown",
    reason:
      "Synthetic PNG fixture is not a device capture; density and insets unmeasured.",
  },
  screenEvidence: { status: "unverified", method: "none" },
  locale: "en-US",
  theme: "light",
  fontScale: 1,
  orientation: "portrait",
  tools: [{ name: "not-executed", version: "1" }],
  normalization: {
    status: "not-applied",
    colorConversion: "none-srgb",
    resampling: "none",
  },
};
const examples = [
  ["SourceSnapshot", source],
  ["Revision", revision],
  ["SemanticPatch", patch],
  [
    "SemanticDiff",
    {
      schemaVersion,
      projectId,
      designId: design.designId,
      before: revisionRef,
      after: dummy("revision_next"),
      changes: patch.operations,
      conflicts: [],
    },
  ],
  ["ReviewEvent", review],
  ["CaptureScenario", scenario],
  ["RenderProfile", profile],
  [
    "BoundsMap",
    {
      schemaVersion,
      projectId,
      renderId: "render_unexecuted_example",
      revision: revisionRef,
      preview: ref(stripe),
      profile: profileRef,
      nodes: {},
    },
  ],
  ["ValidationPolicy", policy],
  ["ValidationReport", validation],
  ["ImplementationPlan", implementation],
  ["HandoffMetadata", metadata],
  ["HandoffManifest", manifestExample],
  ["Job", job],
  [
    "ResponseEnvelope",
    {
      schemaVersion,
      success: true,
      requestId: "request_async",
      data: {
        kind: "accepted-job",
        jobId: job.id,
        status: "queued",
        warnings: [],
      },
    },
  ],
  [
    "ResponseEnvelope",
    {
      schemaVersion,
      success: false,
      requestId: "request_failed",
      error: {
        code: "ACTION_REQUIRED",
        message: "A permitted source session is required.",
        retryable: false,
        jobId: job.id,
        diagnosticIds: [],
      },
    },
  ],
  ["CaptureMetadata", captureMetadata],
  [
    "AuthorizationContext",
    {
      schemaVersion,
      projectId,
      actorId: "actor_synthetic",
      sessionId: "session_synthetic",
      expiresAt: time,
      grants: [
        {
          resourceKind: "design",
          resourceId: design.designId,
          operations: ["read"],
        },
      ],
      egress: "deny",
    },
  ],
  [
    "ProviderCapabilities",
    {
      schemaVersion,
      providerId: "provider_synthetic",
      projectId,
      implementation: "test-fake",
      host: profile.host,
      operations: [
        {
          operation: "readSnapshot",
          availability: "unverified",
          evidence: "unverified",
          limitations: [
            "Seat/plugin and paired transport availability unverified; no wildcard core loopback authorization.",
          ],
        },
      ],
      cancellation: "cooperative",
      deadline: "required",
      limits: budget,
    },
  ],
];
save("contract-examples.json", {
  schemaVersion,
  artifacts: examples.map(([contract, value]) => ({ contract, value })),
});
const files = [
  font,
  ofl,
  mit,
  ...Array.from(outputs, ([path, bytes]) =>
    artifact(
      `fixture_${path.replaceAll(/[^a-zA-Z0-9]/g, "_")}`,
      path,
      path.endsWith(".png") ? "image/png" : "application/json",
      bytes,
    ),
  ),
];
save("manifest.json", {
  schemaVersion,
  id: "foundation_fixtures_v1",
  provenance:
    "Original synthetic authored fixture structures, not P02 DOM probes or real Figma/app content. ABeeZee font unmodified from pinned public OFL source; every other generated asset/structure MIT. Schema-only examples never confer approval or render/capture proof.",
  files,
  cases: fixtureEntries,
});
let drift = 0;
for (const [path, bytes] of outputs) {
  if (process.argv.includes("--check")) {
    let actual;
    try {
      actual = await readFile(new URL(path, root));
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    if (!actual?.equals(bytes)) {
      console.error(`Foundation fixture drift: ${path}`);
      drift++;
    }
  } else {
    await writeFile(new URL(path, root), bytes);
  }
}
if (drift) process.exitCode = 1;
else
  console.log(
    `${process.argv.includes("--check") ? "Checked" : "Generated"} ${outputs.size} synthetic fixture outputs; no renderer or external integration executed.`,
  );
